version: "3"

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/code
        ports:
            - "8080:8080"
        environment:
            - PYTHON_ENV=production
            - DB_NAME=farmerz
            - DB_USERNAME=akshay
            - DB_PASSWORD=IMWWkYItpQeh4rbv8QJJ9-Z8R2Sh1_4l
            - DB_HOST=db
            - DB_PORT=5432
            - DJANGO_SECRET_KEY=django-insecure-hn7mmvfw5@@go%6k4h63&&*1mnx^_i42gi&+j6by@9z+k1&blr
            - ALLOWED_HOSTS=0.0.0.0,localhost
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=akshay
            - POSTGRES_PASSWORD=IMWWkYItpQeh4rbv8QJJ9-Z8R2Sh1_4l
            - POSTGRES_DB=farmerz
