# Generated by Django 4.0.6 on 2022-07-22 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price_per_unit', models.FloatField()),
                ('quantity_unit', models.TextField()),
            ],
        ),
    ]
