# Generated by Django 4.0.6 on 2022-07-22 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.TextField()),
            ],
        ),
    ]
