# Generated by Django 4.0.6 on 2022-07-22 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.TextField()),
                ('village', models.TextField()),
                ('sowing_date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.farmer')),
            ],
        ),
    ]
