# Generated by Django 4.0.6 on 2022-07-22 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.farm')),
                ('fertilizer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.fertilizer')),
            ],
        ),
    ]
