# Generated by Django 4.0.6 on 2022-07-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='crops', to='main.crop'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='farms', to='main.farmer'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='main.farm'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fertilizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='schedule', to='main.fertilizer'),
        ),
    ]
