# Generated by Django 4.0.6 on 2022-07-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_farm_crop_alter_farm_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='farmer',
            field=models.ForeignKey(default='f96a3621-7efd-46d3-8fda-ff2891d3a397', on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='main.farmer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='farms', to='main.crop'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fertilizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.fertilizer'),
        ),
    ]
