# Generated by Django 4.0.6 on 2022-07-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_schedule_farmer_alter_farm_crop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.crop'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.farmer'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.farm'),
        ),
    ]
