# Generated by Django 4.0.6 on 2022-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_schedule_farmer_alter_farm_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='days_after_sowing',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
