# Generated by Django 4.0.6 on 2022-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_schedule_days_after_sowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='sowing_date',
            field=models.DateTimeField(),
        ),
    ]
