# Generated by Django 4.0.6 on 2022-07-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_farm_sowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.fertilizer'),
        ),
    ]
